#!/bin/bash

version=$(cat VERSION)
patch_num=${version##*.}
new_version=${version%.*}.$(($patch_num + 1))
new_version=${1:-$new_version}
echo $new_version > VERSION

git add VERSION
git commit -m "changed version number to $new_version"
git tag v$new_version
git push origin main
git push origin v$new_version

docker build -t mjuul/smtp-client-simple:$new_version .
docker tag mjuul/smtp-client-simple:$new_version mjuul/smtp-client-simple:latest
docker push mjuul/smtp-client-simple:$new_version
docker push mjuul/smtp-client-simple:latest